### ISSUE TITLE
As a developer, I want the front end to be served by the backend

### ISSUE THREAD

**Issue by andrewkucz** [Monicakodali/SEPROJECT#4]
This is for the early stages of the app. Once the initial backend is setup and the front end is set up and has a build directory, we want the backend to serve the index.html file and relevant css/js assets

**Comment by carolnavya** [comment]
To do this, just add "server": "go run server.go" to scripts in package.json. 
This is how it should look like
  "scripts": {
    "start": "react-scripts start",
    "server": "go run main.go",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "proxy": "http://localhost:8080",

Adding a new server command to the scripts section lets us start the API server with _npm run server._ 
Adding the proxy field tells the JavaScript development server to send API requests to our backend instead of just returning a 404 when they don’t match any of the pages defined in the React frontend.

**Comment by andrewkucz** [comment]
> To do this, just add "server": "go run server.go" to scripts in package.json. This is how it should look like "scripts": { "start": "react-scripts start", "server": "go run main.go", "build": "react-scripts build", "test": "react-scripts test", "eject": "react-scripts eject" }, "proxy": "http://localhost:8080",
> 
> Adding a new server command to the scripts section lets us start the API server with _npm run server._ Adding the proxy field tells the JavaScript development server to send API requests to our backend instead of just returning a 404 when they don’t match any of the pages defined in the React frontend.

I think this is a nice command to have but what I meant by this story is for the backend to "serve" the files created by our front end code.

So in the end when we go to `localhost:8080` it should show us our react app. I don't think we have to worry too much about this right now. I can explain more later.

If you want you can put up a PR with that change you mentioned and I can approve it if it works
